### ISSUE TITLE
download a file with ds download

### ISSUE THREAD

**Issue by metter** [MattVador/node-red-contrib-syno#11]
I cannot find any documentation on how to use this nodes. I am trying to download a file from a url. Something that I can do with DS download, but I dont seem to get it to work with the DS Download node. Does somebody have a working example on how to use this node?

**Comment by MattVador** [comment]
Hi metter, you can find documentation on [Synology website](https://global.download.synology.com/download/Document/Software/DeveloperGuide/Package/DownloadStation/All/enu/Synology_Download_Station_Web_API.pdf)

To add a download task, set msg.topic to `createTeask` and msg.payload to `{"uri":"<url file to download>"}`

**Comment by metter** [comment]
That worked! Thank you.
I didnt miss any documentation though, right? I am happy to look this up myself.
Because I already have the next question. Now I want to rename the bespoken file with DS File. My best guess to the necessary payload would be:
topic: `rename`
payload: `{"file":"<url file to file>","name":"<new file name>"}`

**Comment by MattVador** [comment]
Yes except that payload is `{"path":"<path to file>","name":"<new file name>"}`

**Comment by metter** [comment]
Got it thank you. Sorry I didnt see you referenced the Synology documentation earlier on.
Thanks for the integration ;-)

**Comment by RF-Atomik** [comment]
> Got it thank you. Sorry I didnt see you referenced the Synology documentation earlier on.
> Thanks for the integration ;-)

Did you successfully rename a file on your NAs using DS File node ?
I am currently getting this error when I start my flow :  "Error: invalid parameter of file operation"

**Comment by metter** [comment]
> > Got it thank you. Sorry I didnt see you referenced the Synology documentation earlier on.
> > Thanks for the integration ;-)
> 
> Did you successfully rename a file on your NAs using DS File node ?
> I am currently getting this error when I start my flow : "Error: invalid parameter of file operation"

It worked perfectly for a while. Then at one point the flow (pull an mp4 file from a podcast and download it with DS Get) stopped working. As it was a pet project, I never followed up on why - I just assumed they changed something in the podcast XML and I just wouldn't want to go through the process of getting the correct URI again.
But its totally possible that the XML is fine and the problem is with the Synology node.
How did you get the error message from the node? I remember I struggled to get status information from the Synology nodes

**Comment by RF-Atomik** [comment]
> > > Got it thank you. Sorry I didnt see you referenced the Synology documentation earlier on.
> > > Thanks for the integration ;-)
> > 
> > 
> > Did you successfully rename a file on your NAs using DS File node ?
> > I am currently getting this error when I start my flow : "Error: invalid parameter of file operation"
> 
> It worked perfectly for a while. Then at one point the flow (pull an mp4 file from a podcast and download it with DS Get) stopped working. As it was a pet project, I never followed up on why - I just assumed they changed something in the podcast XML and I just wouldn't want to go through the process of getting the correct URI again.
> But its totally possible that the XML is fine and the problem is with the Synology node.
> How did you get the error message from the node? I remember I struggled to get status information from the Synology nodes

That's my Flow to rename a file :
![Screenshot from 2021-01-14 09-56-04](https://user-images.githubusercontent.com/73117162/104567417-0b7bcd00-564f-11eb-97f4-4900a681dd47.png)

In the edit DS File Node, 
- I setup my NAs synology IP address and Port, but I couldn't fill in the good API version, my DSM NAS version is 6.2.3 and is not available on node-red. I don't know it's important or not.
- topic : rename
- payload : {"path":"xxx","name":"xxx"} 

When I deployed my flow that's the status I got.  
![Screenshot from 2021-01-14 09-57-11](https://user-images.githubusercontent.com/73117162/104567615-467e0080-564f-11eb-86dd-397ae959f5ab.png)


I'm starting working on node-red, so I'm not an expert.
