### ISSUE TITLE
DS Audio - Error: Unknown error

### ISSUE THREAD

**Issue by zimmerlis** [MattVador/node-red-contrib-syno#5]
I am able already to use controlRemotePlayer to play an existing playlist on a remote player.
I tried to set a play list by unsing updatePlayListRemotePlayer, but I will always get Error: Unknow error.

var playerID = flow.get('playerID');
var playlistID = flow.get('playlistID');
msg.payload = {
  "library": "shared",
  "id": playerID,
  "limit": 99,
  "offset": 1,
  "containers_json":[{
      "type": "playlist", 
      "id": playlistID
  }]
};
return msg;

**Comment by MattVador** [comment]
An example of payload is 
{
  "library": "shared",
  "id": "uuid:4396499c-9fef-499c-8ff6-3d309883bd92",
  "offset": "0",
  "limit": "0",
  "containers_json": [
    {
      "type": "playlist",
      "id": "playlist_shared_normal/79"
    }
  ]
}

Could you post the message payload valued ?
