### ISSUE TITLE
https: does not save, it keeps switching to http

### ISSUE THREAD

**Issue by armdan** [MattVador/node-red-contrib-syno#7]
http does not save, it keeps switching to http

**Comment by MattVador** [comment]
Hi armdan, can you specify the version of nodejs and node-red please ?

**Comment by armdan** [comment]
Node-red 0.18.4 Node.js v4.4.7 running on Synology NAS docker https://hub.docker.com/r/nodered/node-red-docker/. All other nodes work fine. I installed many other.

**Comment by armdan** [comment]
any updates on the problem ?

**Comment by tedstriker** [comment]
same problem here. Node-RED 0.18.6 Node.js 8.11.2

Update:
seems you already fixed it here: #4 - do you mind publishing it on NPM?

cheers Ted

**Comment by MattVador** [comment]
OK it's my fault, I did not publish on NPM the fix. It's now done.
