### ISSUE TITLE
Flows

### ISSUE THREAD

**Issue by planet4** [MattVador/node-red-contrib-syno#9]
Thanks for sharing this. However I wont get this to work. Would it be possible to get any flows that works so I can see what I am doing wrong?

**Comment by MattVador** [comment]
Hi, this is an example with DS Audio node to get the content playlist of the web player.

`
[{"id":"e81651a8.e05f1","type":"DS Audio","z":"eeb6d1da.77264","dsm":"cecfb491.8e3c98","name":"","topic":"getPlayListWebPlayer","payload":"{\"limit\":\"100\", \"offset\":\"0\"}","x":835,"y":806,"wires":[["f2110449.39c038"]]},{"id":"bd21ae04.3fe99","type":"inject","z":"eeb6d1da.77264","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":605,"y":810,"wires":[["e81651a8.e05f1"]]},{"id":"f2110449.39c038","type":"debug","z":"eeb6d1da.77264","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":1037,"y":813,"wires":[]},{"id":"cecfb491.8e3c98","type":"DS Config","z":"","name":"Conf","protocol":"http","apiVersion":"6.0.2"}]
`
